name: Python CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v3

      # Sets up Python environment
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Installs dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest mock
          sudo apt-get update && sudo apt-get install -y lxc

      # Run linting
      - name: Run linting
        run: |
          pip install flake8
          flake8 src/ tests/ --max-line-length=100 --extend-ignore=E501

      # Run tests with pytest
      - name: Run tests
        run: |
          pytest tests/ -v

      # Cache dependencies
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Notify on failure
      - name: Notify on failure
        if: failure()
        run: |
          echo "Tests failed! Check the logs for details."
