name: Python CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python 3.13.1
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.1'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-mock flake8
          sudo apt-get update && sudo apt-get install -y lxc

      # Cache dependencies
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Run linting
      - name: Run linting
        run: |
          flake8 src/lxc_tui/ --max-line-length=100 --extend-ignore=E501

      # Run tests with pytest
      - name: Run tests
        run: |
          pytest src/tests/ -v

      # Notify on failure
      - name: Notify on failure
        if: failure()
        run: |
          echo "Tests failed! Check the logs for details."